version: "~> 1.0"
os: linux
language: shell
services: docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: M3zhWAroiCfsdhhKP3JH3BrkJodyVmJZ+RYnnSkVq7NjTU07ZDoS9Tkf6Aa4k+30OlYDlbNBE1jOsS1A2Z/OSoRa3pFYqy7K0F0mwvI1ygX3anh4AiWkDhODqCagftCIS3HWF9ddhT+a8qWfwam6zOwBJzdO4fM2QWe5sHhyYlLkLkzkJWogzdr+1XNzd9mhWqm2LZV6G5+Af/KFE2Hyhb8FfSBfrBjY4C5GLQ41htSQUib3Hs5mpt3m7Qhe5Qgc8oIeLefGAS+WAu8hhVbYgsYFrQzL1ObG2ZZDIFxp/cx/q799O8kAdIWw+OCxJLZIOtL2AA3hhHMEs7r9YYzyS1DELQErdrgGJ2nidTw8SZAuhcftilvx8VH1OvDYvubxfWMmAvDIpGHhFvh2jhactWBJbAiOBVQEH02NFhE+uEdFFEw8U6VpM6Jxpiy62MqCXVwgiG+yR7tXIf5NCFg7agaXwcdP1VhUPkH6loh9C8yQbu2qIUKUAkTz0nBqwuPBHqbM9Rzhv+MOEAkg25sSBnZjusZ5wT2JYfCADRzXa3e9djazIdFF6sqm8vvStJuOE+SxMhszhhszhEpMPBrZESp2UY7IgeZWgcChaMZvIFm7l4PdX3AqCYQXDPeMlzHJ7oxj3I+yoVTi3h+3/7M4fjLXlTZJwgCO3ixaGGbcMRI=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
script: .ci/test.sh